<a href="https://colab.research.google.com/github/silentvoice/dl-with-pytorch/blob/master/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Basics

## Install Pytorch

In [2]:
!pip install torch

## Import Packages

In [0]:
import numpy as np

In [0]:
import torch

## Tensor Basics

In [0]:
x = torch.Tensor(4, 5)

In [10]:
x 

tensor([[8.0046e-36, 0.0000e+00, 5.7453e-44, 0.0000e+00,        nan],
        [0.0000e+00, 1.3733e-14, 6.4076e+07, 2.0706e-19, 7.3909e+22],
        [2.4176e-12, 1.1625e+33, 8.9605e-01, 1.1632e+33, 5.6003e-02],
        [7.0374e+22, 5.7453e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [11]:
x.type

<function Tensor.type>

In [12]:
x.shape

torch.Size([4, 5])

In [0]:
y = torch.rand(3, 4)

In [14]:
y

tensor([[0.5244, 0.1087, 0.9364, 0.0778],
        [0.3069, 0.9506, 0.7918, 0.6741],
        [0.4006, 0.5015, 0.0178, 0.7068]])

In [15]:
y.shape

torch.Size([3, 4])

In [0]:
z = torch.zeros(3, 4)

In [17]:
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [0]:
w = torch.ones(5, 5)

In [19]:
w

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [0]:
p = torch.Tensor([[1, 2, 3], [3, 4, 5], [6, 7, 8], [9, 8 ,7 ]])

In [23]:
p

tensor([[1., 2., 3.],
        [3., 4., 5.],
        [6., 7., 8.],
        [9., 8., 7.]])

In [24]:
p.shape

torch.Size([4, 3])

In [0]:
x = np.random.rand(3, 3)

In [26]:
x

array([[0.01598812, 0.77466603, 0.03935295],
       [0.25629081, 0.94027455, 0.63256223],
       [0.29939107, 0.55994937, 0.89746562]])

In [28]:
x.dtype

dtype('float64')

In [29]:
x.shape

(3, 3)

In [0]:
x = torch.from_numpy(x)

In [47]:
x

tensor([[                   0,                    0, -9223372036854775808,
                            1, -4653942449306075136],
        [                   1,                    0,                    1,
                            0,                    1],
        [                   0,                    1,                    0,
                            1, -9223372036854775808],
        [                   1,       -1267446185984,                    1,
                            0,                    0]])

In [48]:
x.shape

torch.Size([4, 5])

In [49]:
x.type()

'torch.LongTensor'

In [0]:
x = x.numpy()

In [35]:
x

array([[0.01598812, 0.77466603, 0.03935295],
       [0.25629081, 0.94027455, 0.63256223],
       [0.29939107, 0.55994937, 0.89746562]])

In [36]:
x.dtype

dtype('float64')

In [0]:
x = torch.Tensor(4, 5)

In [38]:
x

tensor([[ 8.0060e-36,  0.0000e+00,  3.2394e+25,  1.8187e+00, -4.6539e+18],
        [ 1.2824e+00, -6.6689e-29,  1.6281e+00, -9.0711e-14,  1.8601e+00],
        [ 3.6879e-16,  1.7831e+00,  8.2223e-17,  1.6497e+00, -3.7336e+29],
        [ 1.7650e+00, -1.2674e+12,  1.8494e+00,  0.0000e+00,  0.0000e+00]])

In [39]:
x.type

<function Tensor.type>

In [0]:
x = x.long()

In [45]:
x.type()

'torch.LongTensor'

In [46]:
x.float().type()

'torch.FloatTensor'

## Tensor Operations

In [0]:
x = torch.Tensor(3, 4)

In [0]:
y = torch.Tensor(3, 4)

In [0]:
z = x + y 

In [54]:
x.shape

torch.Size([3, 4])

In [55]:
y.shape

torch.Size([3, 4])

In [56]:
x

tensor([[8.0143e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [57]:
y

tensor([[8.0144e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [58]:
z

tensor([[1.6029e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [59]:
z.shape

torch.Size([3, 4])

In [0]:
x = torch.rand(3, 4)

In [0]:
y = torch.rand(4, 5)

In [0]:
z = torch.mm(x, y)

In [63]:
x.shape

torch.Size([3, 4])

In [64]:
x

tensor([[0.0674, 0.7851, 0.7490, 0.7091],
        [0.1729, 0.2071, 0.7311, 0.2385],
        [0.2396, 0.6782, 0.0447, 0.0447]])

In [65]:
y.shape

torch.Size([4, 5])

In [66]:
y

tensor([[0.0209, 0.4069, 0.5316, 0.4588, 0.7976],
        [0.3882, 0.3259, 0.3809, 0.5297, 0.4407],
        [0.2917, 0.1186, 0.5658, 0.3502, 0.4136],
        [0.0418, 0.7767, 0.4202, 0.7049, 0.4005]])

In [67]:
z.shape

torch.Size([3, 5])

In [68]:
z

tensor([[0.5542, 0.9229, 1.0566, 1.2090, 0.9935],
        [0.3072, 0.4098, 0.6847, 0.6132, 0.6271],
        [0.2832, 0.3586, 0.4298, 0.5164, 0.5264]])

In [0]:
z = torch.t(z)

In [70]:
z

tensor([[0.5542, 0.3072, 0.2832],
        [0.9229, 0.4098, 0.3586],
        [1.0566, 0.6847, 0.4298],
        [1.2090, 0.6132, 0.5164],
        [0.9935, 0.6271, 0.5264]])

In [71]:
z.shape

torch.Size([5, 3])

In [74]:
z.t()

tensor([[0.5542, 0.9229, 1.0566, 1.2090, 0.9935],
        [0.3072, 0.4098, 0.6847, 0.6132, 0.6271],
        [0.2832, 0.3586, 0.4298, 0.5164, 0.5264]])

In [75]:
z.shape

torch.Size([5, 3])

In [80]:
z.contiguous().view(3, 5)

tensor([[0.5542, 0.3072, 0.2832, 0.9229, 0.4098],
        [0.3586, 1.0566, 0.6847, 0.4298, 1.2090],
        [0.6132, 0.5164, 0.9935, 0.6271, 0.5264]])

In [0]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])

In [82]:
x. shape

torch.Size([2, 3])

In [83]:
x.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [84]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [85]:
torch.sum(x, dim=0)

tensor([5., 7., 9.])

In [86]:
torch.sum(x, dim=1)

tensor([ 6., 15.])

In [87]:
x.sum(dim=0)

tensor([5., 7., 9.])

In [88]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
x = x.sum(dim=0)

In [91]:
x

tensor([5., 7., 9.])

## Gradients

In [0]:
x = torch.rand(3, 3, requires_grad=True)

In [0]:
y = x**3 + 7

In [0]:
z = y.sum(dim=0)

In [107]:
z

tensor([21.2356, 21.3985, 21.9474], grad_fn=<SumBackward2>)

In [0]:
z = z.sum()

In [109]:
z

tensor(64.5816, grad_fn=<SumBackward0>)

In [0]:
x.grad

In [0]:
z.backward()

In [115]:
x.grad

tensor([[0.2586, 0.1333, 2.8649],
        [0.8085, 0.3011, 0.0201],
        [0.5116, 1.5108, 0.1711]])